repos:

  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3.8
        exclude: >
          (?x)^(
            scripts/gen-docs-index|
          )$

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: fix-encoding-pragma
      - id: trailing-whitespace

  - repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.7.9
    hooks:
      - id: flake8

  - repo: git://github.com/igorshubovych/markdownlint-cli
    rev: v0.22.0
    hooks:
      - id: markdownlint
        entry: markdownlint --ignore .github/*.md

  - repo: git://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
      - id: shell-lint
