version: "3.3"

services:
  web:
    container_name: milmove_admin
    build:
      context: ./app
      dockerfile: Dockerfile.prod
      cache_from:
        - python:3.8-alpine3.11
    command: milmove_admin.wsgi:application --name milmove_admin --bind 0.0.0.0:8000 --workers 3 --log-level info --error-logfile "-" --access-logfile "-"
    image: milmove_admin:latest
    stdin_open: true
    tty: true
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    environment:
      - LOCAL_HOST_NAME
      - DJANGO_ALLOWED_HOSTS
      - DJANGO_DEBUG
      - DJANGO_SECRET_KEY
      - DB_ENGINE
      - DB_PASSWORD
      - PGPASSWORD
      - DB_USER
      - DB_HOST=db
      - DB_PORT
      - DB_NAME
      - LOGIN_GOV_CALLBACK_PROTOCOL
      - LOGIN_GOV_CALLBACK_PORT
      - LOGIN_GOV_ENGADMIN_CLIENT_ID
      - LOGIN_GOV_HOSTNAME
      - LOGIN_GOV_KID_JWK
      - LOGIN_GOV_JWK_SET_FILENAME
      - LOGIN_GOV_SECRET_KEY
    external_links:
      - milmove-db-dev:db

  nginx:
    container_name: milmove_admin_nginx
    build: ./nginx
    image: milmove_admin_nginx:latest
    stdin_open: false
    tty: true
    ports:
      - "3000:80"
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - web

volumes:
  static_volume:

networks:
  default:
    external:
      name: dbnet
