version: "3.3"

services:
  web:
    build: ./app
    command: runserver 0.0.0.0:8001
    ports:
      - 8001:8001
    volumes:
      - ./app/:/usr/src/app/
    environment:
      - DJANGO_ALLOWED_HOSTS
      - DJANGO_DEBUG
      - DJANGO_SECRET_KEY
      - DB_ENGINE
      - DB_PASSWORD
      - PGPASSWORD
      - DB_USER
      - DB_HOST=db
      - DB_PORT
      - DB_NAME
    external_links:
      - milmove-db-dev:db

networks:
  default:
    external:
      name: dbnet
