#!/usr/bin/env bash

LOGIN_GOV_SECRET_KEY=$(echo $B64_LOGIN_GOV_SECRET_KEY | base64 --decode) python ./scripts/convert_key_to_jwk_set.py #todo: remove LOGIN_GOV_SECRET_KEY & LOGIN_GOV_KID_JWK from circle ci env variables once we land a better way to handle LOGIN_GOV_JWK_SET_FILENAME
