#! /usr/bin/env bash

set -eu -o pipefail

prereqs_found=true

function has() {
    local tool=$1
    local tool_install_direction=$2
    if [[ -n $(type -p "${tool}") ]]; then
        echo "${tool} installed."
    else
        echo "WARNING: ${tool} not found, install via: ${tool_install_direction}"
        prereqs_found=false
    fi
}

has python "brew install python"
has virtualenv "pip3 install virtualenv"
has pre-commit "brew install pre-commit"
has shellcheck "brew install shellcheck"
has docker "Get Docker CE for Mac from https://download.docker.com/mac/stable/Docker.dmg"

# not on CircleCI
if [[ -z ${CIRCLECI-} ]]; then
    has direnv "brew install direnv"
fi


if [[ $prereqs_found == "true" ]]; then
    echo "OK: all prereqs found"
else
    echo "ERROR: some prereqs missing, please install them"
    exit 1
fi
