#! /usr/bin/env bash

#
# Run the django admin inside docker
#
# This script creates a special docker network to connect the milmove db to the django admin container.
# It then runs the container using docker-compose.
#

set -u -o pipefail

if [ -n "${VIRTUAL_ENV+x}" ]; then
  echo "Running in Virtual Environment!"
else
  echo "Must run from a Virtual Environment!"
  echo "Run 'source .venv/bin/activate' to activate"
  echo "Or run 'make runserver_docker' instead"
  exit 1
fi

# Generate new static files
python manage.py collectstatic --noinput --clear

NETWORK=dbnet

# Check if the network has already been set up before creating one
if docker network inspect "${NETWORK}" > /dev/null ; then
  echo "Network ${NETWORK} already created"
else
  docker network create "${NETWORK}"
  docker network connect "${NETWORK}" milmove-db-dev
fi

docker-compose up --build
docker-compose down
